export const budgetSagaActions = {
    CREATE_BUDGET: 'CREATE_BUDGET',
    CHECK_ACTIVE_BUDGET: 'CHECK_ACTIVE_BUDGET',
    ADD_EXPENSE: 'ADD_EXPENSE',
    ADD_INCOME: 'ADD_INCOME',
    ADD_RESERVE: 'ADD_RESERVE',
}